### ISSUE TITLE
Make new icon-button demo page from 0.36.0-0 prerelease

### ISSUE THREAD

**Issue by williamernest** [material-components/material-components-web-catalog#156]
The `mdc-icon-toggle` package was deprecated in v0.36.0 in favor of `mdc-icon-button`. 

- [x] Update `IconToggleCatalogPage.js` -> `IconButtonCatalogPage.js`
- [x] Add demo for icon buttons without toggle behavior. 
- [x] Update `ThemeCatalog.js` use of IconToggle
- [x] Update `CardCatalogPage.js` to use new `mdc-icon-button`

https://github.com/material-components/material-components-web/pull/2748

**Comment by williamernest** [comment]
Resolved with #161
